/*
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CcslStandaloneSetup extends CcslStandaloneSetupGenerated {

	def static void doSetup() {
		new CcslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
