/*
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.ide

import com.google.inject.Guice
import org.ccsl.xtext.CcslRuntimeModule
import org.ccsl.xtext.CcslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CcslIdeSetup extends CcslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CcslRuntimeModule, new CcslIdeModule))
	}
	
}
