/**
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.ccsl.xtext.CcslRuntimeModule;
import org.ccsl.xtext.CcslStandaloneSetup;
import org.ccsl.xtext.ide.CcslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CcslIdeSetup extends CcslStandaloneSetup {
  @Override
  public Injector createInjector() {
    CcslRuntimeModule _ccslRuntimeModule = new CcslRuntimeModule();
    CcslIdeModule _ccslIdeModule = new CcslIdeModule();
    return Guice.createInjector(Modules2.mixin(_ccslRuntimeModule, _ccslIdeModule));
  }
}
