/**
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.ide;

import org.ccsl.xtext.ide.AbstractCcslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CcslIdeModule extends AbstractCcslIdeModule {
}
