/**
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.ui;

import org.ccsl.xtext.ui.AbstractCcslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CcslUiModule extends AbstractCcslUiModule {
  public CcslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
