/**
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.scoping;

import org.ccsl.xtext.scoping.AbstractCcslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CcslScopeProvider extends AbstractCcslScopeProvider {
}
