<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ccsl" nsURI="http://www.example.org/ccsl" nsPrefix="ccsl">
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true" eSuperTypes="#//Root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeRule" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//LogicOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="2" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicRule" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//elements/Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//context/Context" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicOperator">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaultTypeDescription" eSuperTypes="#//Root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="#//AtomicRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//faultTypeDescription/InjectionAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategies" lowerBound="1"
        upperBound="-1" eType="#//faultTypeDescription/InjectionStrategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionKind">
    <eLiterals name="EXACT"/>
    <eLiterals name="SEQUENCE" value="1"/>
    <eLiterals name="ANY" value="2"/>
    <eLiterals name="IMMEDIATE" value="3"/>
  </eClassifiers>
  <eSubpackages name="elements" nsURI="http://www.example.org/ccsl/elements" nsPrefix="elements">
    <eClassifiers xsi:type="ecore:EClass" name="Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
      <eLiterals name="PRIVATE"/>
      <eLiterals name="PACKAGE" value="1"/>
      <eLiterals name="PROTECTED" value="2"/>
      <eLiterals name="PUBLIC" value="3"/>
      <eLiterals name="ANY" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Inheritance">
      <eLiterals name="ABSTRACT"/>
      <eLiterals name="FINAL" value="1"/>
      <eLiterals name="NONE" value="2"/>
      <eLiterals name="ANY" value="3"/>
    </eClassifiers>
    <eSubpackages name="namedElements" nsURI="http://www.example.org/ccsl/elements/namedElements"
        nsPrefix="namedElements">
      <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="#//elements/Element">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
            unsettable="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableInSourceCode"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//elements/namedElements/NamedElement #//elements/statements/import/ImportableElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declaredTypes" upperBound="-1"
            eType="#//elements/namedElements/complexType/TypeDeclaration" unsettable="true"
            containment="true"/>
      </eClassifiers>
      <eSubpackages name="variable" nsURI="http://www.example.org/ccsl/elements/namedElements/variable"
          nsPrefix="variable">
        <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//elements/namedElements/NamedElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/DataType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"
              unsettable="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ParameterVariable" eSuperTypes="#//elements/namedElements/variable/Variable http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="#//elements/namedElements/variable/InitializableVariable"/>
        <eClassifiers xsi:type="ecore:EClass" name="InitializableVariable" eSuperTypes="#//elements/namedElements/variable/Variable">
          <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" eType="#//elements/statements/Statement"
              unsettable="true" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="FieldVariable" eSuperTypes="#//elements/namedElements/variable/InitializableVariable">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//elements/Visibility"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="complexType" nsURI="http://www.example.org/ccsl/elements/namedElements/complexType"
          nsPrefix="complexType">
        <eClassifiers xsi:type="ecore:EClass" name="JInterface" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EObject #//elements/namedElements/complexType/ComplexTypeDeclaration"/>
        <eClassifiers xsi:type="ecore:EClass" name="AnonymousClass" eSuperTypes="#//elements/namedElements/complexType/ComplexType #//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/ObjectType"
              unsettable="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="JClass" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EObject #//elements/namedElements/complexType/ConstructComplexTypeDeclaration">
          <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="#//elements/namedElements/complexType/JClass"
              unsettable="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritance" eType="#//elements/Inheritance"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" eSuperTypes="#//elements/namedElements/NamedElement #//elements/datatype/ObjectType #//elements/statements/import/ImportableElement">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
              eType="#//elements/statements/import/ImportStatement" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="nestedTypes" upperBound="-1"
              eType="#//elements/namedElements/complexType/TypeDeclaration" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="importsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//elements/Element">
          <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
              eType="#//elements/namedElements/variable/FieldVariable" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
              eType="#//elements/namedElements/method/Method" unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="AnnotationType" eSuperTypes="#//elements/namedElements/complexType/TypeDeclaration">
          <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
              eType="#//elements/namedElements/complexType/AnnotationField" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="AnnotationField" eSuperTypes="#//elements/namedElements/NamedElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//elements/expressions/Expression"
              unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/DataType"
              unsettable="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="JEnum" eSuperTypes="#//elements/namedElements/complexType/ConstructComplexTypeDeclaration">
          <eStructuralFeatures xsi:type="ecore:EReference" name="enumConstants" upperBound="-1"
              eType="#//elements/namedElements/complexType/EnumConstant" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumConstantsKind"
              eType="#//CollectionKind" defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ComplexTypeDeclaration" eSuperTypes="#//elements/namedElements/complexType/TypeDeclaration #//elements/namedElements/complexType/ComplexType">
          <eStructuralFeatures xsi:type="ecore:EReference" name="superInterfaces"
              upperBound="-1" eType="#//elements/namedElements/complexType/JInterface"
              unsettable="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//elements/Visibility"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ConstructComplexTypeDeclaration"
            eSuperTypes="#//elements/namedElements/complexType/ComplexTypeDeclaration">
          <eStructuralFeatures xsi:type="ecore:EReference" name="constructors" upperBound="-1"
              eType="#//elements/namedElements/method/Constructor" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="constructorsKind"
              eType="#//CollectionKind" defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EnumConstant" eSuperTypes="#//elements/namedElements/NamedElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
              eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="argumentsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="method" nsURI="http://www.example.org/ccsl/elements/namedElements/method"
          nsPrefix="method">
        <eClassifiers xsi:type="ecore:EClass" name="Constructor" eSuperTypes="#//elements/namedElements/method/SimpleMethod">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="avaliableInSourceCode"
              eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SimpleMethod" eSuperTypes="#//elements/Element http://www.eclipse.org/emf/2002/Ecore#//EObject">
          <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
              eType="#//elements/namedElements/variable/ParameterVariable" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//elements/Visibility"
              defaultValueLiteral="ANY"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//elements/namedElements/NamedElement #//elements/namedElements/method/SimpleMethod">
          <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//elements/datatype/DataType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"
              unsettable="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritance" eType="#//elements/Inheritance"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="statements" nsURI="http://www.example.org/ccsl/elements/statements"
        nsPrefix="statements">
      <eClassifiers xsi:type="ecore:EClass" name="Statement" eSuperTypes="#//elements/Element"/>
      <eClassifiers xsi:type="ecore:EClass" name="ControlFlowStatement" eSuperTypes="#//elements/statements/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//elements/statements/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
            eType="#//elements/statements/Statement" unsettable="true" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="statementsKind" eType="#//CollectionKind"
            defaultValueLiteral="ANY"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceCreation" eSuperTypes="#//elements/statements/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/ObjectType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" eType="#//elements/namedElements/method/Constructor"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1"
            eType="#//elements/statements/Statement" unsettable="true" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="argsKind" eType="#//CollectionKind"
            defaultValueLiteral="ANY"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SynchronizedBlock" eSuperTypes="#//elements/statements/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="bodyStatements" upperBound="-1"
            eType="#//elements/statements/Statement" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//elements/statements/Statement"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ThrowStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//elements/statements/Statement"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EmptyStatement" eSuperTypes="#//elements/statements/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#//elements/statements/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//elements/statements/Statement"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BreakStatement" eSuperTypes="#//elements/statements/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ContinueStatement" eSuperTypes="#//elements/statements/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="AssertStatement" eSuperTypes="#//elements/statements/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//elements/expressions/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//elements/expressions/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#//elements/statements/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
            eType="#//elements/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eSubpackages name="controlFlow" nsURI="http://www.example.org/ccsl/elements/statements/controlFlow"
          nsPrefix="controlFlow">
        <eClassifiers xsi:type="ecore:EClass" name="SwitchStatement" eSuperTypes="#//elements/statements/controlFlow/ConditionalControlFlowStatement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
              eType="#//elements/statements/controlFlow/SwitchCaseBlock" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SwitchCaseBlock" eSuperTypes="#//elements/statements/Block">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="caseExpression" eType="#//elements/expressions/Expression"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//elements/statements/controlFlow/ConditionalControlFlowStatement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="thenStatement" eType="#//elements/statements/Statement"
              unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatement" eType="#//elements/statements/Statement"
              unsettable="true" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="LoopStatement" eSuperTypes="#//elements/statements/ControlFlowStatement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//elements/statements/Statement"
              unsettable="true" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//elements/statements/controlFlow/LoopStatement"/>
        <eClassifiers xsi:type="ecore:EClass" name="DoStatement" eSuperTypes="#//elements/statements/controlFlow/ConditionalControlFlowStatement #//elements/statements/controlFlow/LoopStatement"/>
        <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//elements/statements/controlFlow/LoopStatement #//elements/statements/controlFlow/ConditionalControlFlowStatement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="initializers" upperBound="-1"
              eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="initializersKind"
              eType="#//CollectionKind"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="updaters" upperBound="-1"
              eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatersKind" eType="#//CollectionKind"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ForEachStatement" eSuperTypes="#//elements/statements/controlFlow/LoopStatement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//elements/statements/controlFlow/LoopStatement"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//elements/namedElements/variable/ParameterVariable"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ConditionalControlFlowStatement"
            eSuperTypes="#//elements/statements/ControlFlowStatement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//elements/expressions/Expression"
              containment="true"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="tryCatch" nsURI="http://www.example.org/ccsl/elements/statements/tryCatch"
          nsPrefix="tryCatch">
        <eClassifiers xsi:type="ecore:EClass" name="TryStatement" eSuperTypes="#//elements/statements/Statement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="catchClauses" upperBound="-1"
              eType="#//elements/statements/tryCatch/CatchClause" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="finallyBlock" eType="#//elements/statements/Block"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="catchClausesKind"
              eType="#//CollectionKind" defaultValueLiteral="ANY"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
              eType="#//elements/expressions/Expression" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourcesKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CatchClause" eSuperTypes="#//elements/statements/Statement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//elements/statements/Block"
              unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//elements/namedElements/variable/ParameterVariable"
              unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="handledExceptions"
              upperBound="-1" eType="#//elements/namedElements/complexType/JClass"
              unsettable="true"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="import" nsURI="http://www.example.org/ccsl/elements/statements/import"
          nsPrefix="import">
        <eClassifiers xsi:type="ecore:EClass" name="ImportableElement" eSuperTypes="#//elements/Element"/>
        <eClassifiers xsi:type="ecore:EClass" name="ImportStatement" eSuperTypes="#//elements/statements/Statement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="importedElement"
              eType="#//elements/statements/import/ImportableElement" unsettable="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
              unsettable="true"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="datatype" nsURI="http://www.example.org/ccsl/elements/datatype"
        nsPrefix="datatype">
      <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//elements/Element"/>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//elements/datatype/DataType"/>
      <eClassifiers xsi:type="ecore:EClass" name="StringPrimitiveType" eSuperTypes="#//elements/datatype/PrimitiveType"/>
      <eClassifiers xsi:type="ecore:EClass" name="BooleanPrimitiveType" eSuperTypes="#//elements/datatype/PrimitiveType"/>
      <eClassifiers xsi:type="ecore:EClass" name="ShortPrimitiveType" eSuperTypes="#//elements/datatype/PrimitiveType"/>
      <eClassifiers xsi:type="ecore:EClass" name="ObjectType" eSuperTypes="#//elements/datatype/DataType"/>
      <eClassifiers xsi:type="ecore:EClass" name="ParameterizedType" eSuperTypes="#//elements/datatype/ObjectType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
            eType="#//elements/datatype/ObjectType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/namedElements/complexType/TypeDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GenericType" eSuperTypes="#//elements/namedElements/complexType/ComplexType"/>
      <eClassifiers xsi:type="ecore:EClass" name="IntPrimitiveType" eSuperTypes="#//elements/datatype/PrimitiveType"/>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//elements/datatype/ObjectType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensions" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
            unsettable="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/DataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//elements/datatype/PrimitiveType"/>
    </eSubpackages>
    <eSubpackages name="expressions" nsURI="http://www.example.org/ccsl/elements/expressions"
        nsPrefix="expressions">
      <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//elements/Element"/>
      <eClassifiers xsi:type="ecore:EClass" name="VarDeclaration" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//elements/namedElements/variable/Variable"
            unsettable="true" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CastExpression" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//elements/expressions/Expression"
            unsettable="true" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/DataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TernaryExpression" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//elements/expressions/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" eType="#//elements/expressions/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" eType="#//elements/expressions/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceOfExpression" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/ObjectType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//elements/expressions/Expression"
            unsettable="true" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="-1"
            eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="arithmeticKind" eType="#//elements/expressions/ExpressionKind"
            defaultValueLiteral="ANY"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//elements/expressions/ArithmeticOperator"
            defaultValueLiteral="ANY"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operandsKind" eType="#//CollectionKind"
            defaultValueLiteral="ANY"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ExpressionKind">
        <eLiterals name="INFIX"/>
        <eLiterals name="UNARY" value="1"/>
        <eLiterals name="ANY" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperator">
        <eLiterals name="ADDITION"/>
        <eLiterals name="MULTIPLICATION" value="1"/>
        <eLiterals name="DIVIDE" value="2"/>
        <eLiterals name="SUBTRACT" value="3"/>
        <eLiterals name="ANY" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringConcatenation" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="-1"
            eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operandsKind" eType="#//CollectionKind"
            defaultValueLiteral="ANY"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operandsKind" eType="#//CollectionKind"
            defaultValueLiteral="ANY"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//elements/expressions/ExpressionKind"
            defaultValueLiteral="ANY"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="-1"
            eType="#//elements/expressions/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//elements/expressions/BooleanOperator"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//elements/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//elements/expressions/ExpressionKind"
            defaultValueLiteral="ANY"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//elements/expressions/BinaryOperator"
            defaultValueLiteral="ANY"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operandsKind" eType="#//CollectionKind"
            defaultValueLiteral="ANY"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="-1"
            eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="BooleanOperator">
        <eLiterals name="AND"/>
        <eLiterals name="OR" value="1"/>
        <eLiterals name="NEGATED" value="2"/>
        <eLiterals name="ANY" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
        <eLiterals name="LEFT_SHIFT"/>
        <eLiterals name="RIGHT_SHIFT" value="1"/>
        <eLiterals name="UNSIGNED_LEFT_SHIFT" value="2"/>
        <eLiterals name="UNSIGNED_RIGHT_SHIFT" value="3"/>
        <eLiterals name="COMPLEMENT" value="4"/>
        <eLiterals name="ANY" value="5"/>
      </eClassifiers>
      <eSubpackages name="invocations" nsURI="http://www.example.org/ccsl/elements/expressions/invocations"
          nsPrefix="invocations">
        <eClassifiers xsi:type="ecore:EClass" name="MethodInvocation" eSuperTypes="#//elements/expressions/invocations/Invocation">
          <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//elements/statements/Statement"
              unsettable="true" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Invocation" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="argsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//elements/namedElements/method/SimpleMethod"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1"
              eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ConstructorInvocation" eSuperTypes="#//elements/expressions/invocations/Invocation">
          <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" eType="#//elements/namedElements/method/Constructor"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="accesses" nsURI="http://www.example.org/ccsl/elements/expressions/accesses"
          nsPrefix="accesses">
        <eClassifiers xsi:type="ecore:EClass" name="VariableAccess" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//elements/namedElements/variable/Variable"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DataTypeAccess" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="#//elements/datatype/DataType"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="arrays" nsURI="http://www.example.org/ccsl/elements/expressions/arrays"
          nsPrefix="arrays">
        <eClassifiers xsi:type="ecore:EClass" name="ArrayCreation" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/datatype/ObjectType"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="#//elements/expressions/arrays/ArrayInitializer"
              unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
              eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensionsKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ArrayIndexesAccess" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
              eType="#//elements/expressions/Expression" unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexesKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ArrayInitializer" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
              eType="#//elements/expressions/Expression" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="valuesKind" upperBound="-1"
              eType="#//CollectionKind" defaultValueLiteral="ANY" unsettable="true"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="assignment" nsURI="http://www.example.org/ccsl/elements/statements/assignment"
          nsPrefix="assignment">
        <eClassifiers xsi:type="ecore:EClass" name="SimpleAssignment" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//elements/expressions/Expression"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="AssignmentOperator">
          <eLiterals name="PLUS_ASSIGN"/>
          <eLiterals name="ASSIGN" value="1"/>
          <eLiterals name="ANY" value="2"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//elements/expressions/assignment/SimpleAssignment">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//elements/expressions/assignment/AssignmentOperator"
              defaultValueLiteral="ANY"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//elements/expressions/Expression"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="UnaryAssignment" eSuperTypes="#//elements/expressions/assignment/SimpleAssignment">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//elements/expressions/assignment/UnaryAssignmentKind"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//elements/expressions/assignment/UnaryAssignmentOperator"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="UnaryAssignmentOperator">
          <eLiterals name="DECREMENT"/>
          <eLiterals name="INCREMENT" value="1"/>
          <eLiterals name="ANY" value="2"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="UnaryAssignmentKind">
          <eLiterals name="POST"/>
          <eLiterals name="PRE" value="1"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="literals" nsURI="http://www.example.org/ccsl/elements/statements/literals"
          nsPrefix="literals">
        <eClassifiers xsi:type="ecore:EClass" name="LiteralValue" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="#//elements/expressions/literals/LiteralValue"/>
        <eClassifiers xsi:type="ecore:EClass" name="CharacterLiteral" eSuperTypes="#//elements/expressions/literals/LiteralValue"/>
        <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//elements/expressions/literals/LiteralValue"/>
        <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//elements/expressions/literals/LiteralValue"/>
        <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//elements/expressions/literals/LiteralValue"/>
      </eSubpackages>
      <eSubpackages name="annotation" nsURI="http://www.example.org/ccsl/elements/expressions/annotation"
          nsPrefix="annotation">
        <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//elements/expressions/Expression">
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/namedElements/complexType/AnnotationType"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
              eType="#//elements/expressions/annotation/AnnotationFieldValue" unsettable="true"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="valuesKind" eType="#//CollectionKind"
              defaultValueLiteral="ANY"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="AnnotationFieldValue">
          <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//elements/expressions/Expression"
              unsettable="true" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//elements/namedElements/complexType/AnnotationField"
              unsettable="true"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="context" nsURI="http://www.example.org/ccsl/context" nsPrefix="context">
    <eClassifiers xsi:type="ecore:EClass" name="Context">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contextElements" upperBound="-1"
          eType="#//elements/Element" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
          eType="#//functions/booleanFunctions/filters/Filter" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="faultTypeDescription" nsURI="http://www.example.org/ccsl/faultTypeDescription"
      nsPrefix="faultTypeDescription">
    <eClassifiers xsi:type="ecore:EClass" name="InjectionAction" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//elements/Element"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InjectionStrategy" abstract="true"/>
    <eSubpackages name="action" nsURI="http://www.example.org/ccsl/faultTypeDescription/action"
        nsPrefix="action">
      <eClassifiers xsi:type="ecore:EClass" name="DeleteAction" eSuperTypes="#//faultTypeDescription/InjectionAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="MoveScopeUpAction" eSuperTypes="#//faultTypeDescription/InjectionAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="DeleteInfixOperatorAction" eSuperTypes="#//faultTypeDescription/InjectionAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="ChangeLiteralValueAction" eSuperTypes="#//faultTypeDescription/InjectionAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="DeleteRandomStatementAction" eSuperTypes="#//faultTypeDescription/InjectionAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceVariableAccessAction" eSuperTypes="#//faultTypeDescription/InjectionAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceArithmeticOperatorAction"
          eSuperTypes="#//faultTypeDescription/InjectionAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="replaceMap" lowerBound="1"
            upperBound="-1" eType="#//faultTypeDescription/action/ArithmeticOperatorMap"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArithmeticOperatorMap">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldArithmeticOperator"
            eType="#//elements/expressions/ArithmeticOperator"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newArithmeticOperator"
            eType="#//elements/expressions/ArithmeticOperator"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="strategy" nsURI="http://www.example.org/ccsl/faultTypeDescription/strategy"
        nsPrefix="strategy">
      <eClassifiers xsi:type="ecore:EClass" name="AllStrategy" eSuperTypes="#//faultTypeDescription/InjectionStrategy"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="functions" nsURI="http://www.example.org/ccsl/functions" nsPrefix="functions">
    <eClassifiers xsi:type="ecore:EClass" name="CcslFunction" abstract="true"/>
    <eSubpackages name="booleanFunctions" nsURI="http://www.example.org/ccsl/functions/booleanFunctions"
        nsPrefix="booleanFunctions">
      <eClassifiers xsi:type="ecore:EClass" name="CcslBooleanFunction" abstract="true"
          eSuperTypes="#//functions/CcslFunction"/>
      <eSubpackages name="filters" nsURI="http://www.example.org/ccsl/filters" nsPrefix="filters">
        <eClassifiers xsi:type="ecore:EClass" name="Filter" abstract="true" eSuperTypes="#//functions/booleanFunctions/CcslBooleanFunction">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="AtomicFilter" eSuperTypes="#//functions/booleanFunctions/filters/Filter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="1"
              upperBound="-1" eType="#//elements/Element"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CompositeFilter" eSuperTypes="#//functions/booleanFunctions/filters/Filter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="filters" lowerBound="1"
              upperBound="-1" eType="#//functions/booleanFunctions/filters/Filter"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//LogicOperator"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PropertyFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter"/>
        <eClassifiers xsi:type="ecore:EClass" name="TemplateFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="targetTemplate" lowerBound="1"
              eType="#//elements/Element"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
              eType="#//context/Context" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SameNameFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
              eType="#//elements/namedElements/NamedElement"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreCase" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
              defaultValueLiteral="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CountFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
              upperBound="-1" eType="#//context/Context" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//elements/Element"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1"
              eType="#//elements/Element"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="RegexMatch" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="regex" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ImplicityOperandFilter" eSuperTypes="#//functions/booleanFunctions/filters/TemplateFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="implicityOperand"
              lowerBound="1" eType="#//elements/Element"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
              eType="#//elements/expressions/Expression"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ImplicityContainerFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="implicityContainer"
              lowerBound="1" eType="#//elements/Element"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="implicityField" lowerBound="1"
              eType="#//elements/Element"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
              eType="#//context/Context" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IsKindOfFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
              eType="#//context/Context" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
              eType="#//elements/datatype/DataType"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SuperMethodClosureFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
              eType="#//context/Context" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="superMethod" lowerBound="1"
              eType="#//elements/namedElements/method/Method"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IsTypeOfFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
              eType="#//context/Context" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
              eType="#//elements/datatype/DataType"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ChildClosureComplexTypeFilter"
            eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="superComplexType"
              lowerBound="1" eType="#//elements/namedElements/complexType/ComplexType"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="childComplexType"
              lowerBound="1" eType="#//elements/namedElements/complexType/ComplexType"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
              eType="#//context/Context" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IsStringFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter"/>
        <eClassifiers xsi:type="ecore:EClass" name="EquationFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="leftHandSide" lowerBound="1"
              upperBound="-1" eType="#//functions/numberFunctions/CcslNumberFunction"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="rightHandSide" lowerBound="1"
              upperBound="-1" eType="#//functions/numberFunctions/CcslNumberFunction"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//functions/booleanFunctions/filters/EquationOperator"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="EquationOperator">
          <eLiterals name="PLUS"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="FromClosureFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
              eType="#//elements/statements/Statement"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//context/Context"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SuperClassClosureFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="#//elements/namedElements/complexType/JClass"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="subClass" eType="#//elements/namedElements/complexType/JClass"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="includesSubClass"
              eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
              defaultValueLiteral="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//context/Context"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="BlockLastStatementFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter">
          <eStructuralFeatures xsi:type="ecore:EReference" name="lastStatement" eType="#//elements/statements/Statement"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//context/Context"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HasSameReferenceFilter" eSuperTypes="#//functions/booleanFunctions/filters/AtomicFilter"/>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="numberFunctions" nsURI="http://www.example.org/ccsl/functions/numberFunctions"
        nsPrefix="numberFunctions">
      <eClassifiers xsi:type="ecore:EClass" name="CcslNumberFunction" abstract="true"
          eSuperTypes="#//functions/CcslFunction"/>
      <eClassifiers xsi:type="ecore:EClass" name="CcslIntegerLiteral" eSuperTypes="#//functions/numberFunctions/CcslNumberFunction">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GetIndexOf" eSuperTypes="#//functions/numberFunctions/CcslNumberFunction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
            eType="#//elements/Element"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1"
            eType="#//elements/Element"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
