/**
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.validation;

import org.ccsl.xtext.validation.AbstractCcslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CcslValidator extends AbstractCcslValidator {
}
