/**
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.ui.contentassist;

import org.ccsl.xtext.ui.contentassist.AbstractCcslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CcslProposalProvider extends AbstractCcslProposalProvider {
}
