/**
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext;

import org.ccsl.xtext.AbstractCcslRuntimeModule;
import org.ccsl.xtext.CcslQualifiedNameProvider;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CcslRuntimeModule extends AbstractCcslRuntimeModule {
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return CcslQualifiedNameProvider.class;
  }
}
