/*
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CcslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/ccsl/xtext/parser/antlr/internal/InternalCcsl.tokens");
	}
}
