/*
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.parser.antlr;

import com.google.inject.Inject;
import org.ccsl.xtext.parser.antlr.internal.InternalCcslParser;
import org.ccsl.xtext.services.CcslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CcslParser extends AbstractAntlrParser {

	@Inject
	private CcslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCcslParser createParser(XtextTokenStream stream) {
		return new InternalCcslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Rule";
	}

	public CcslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CcslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
