/*
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.ui.tests;

import com.google.inject.Injector;
import org.ccsl.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CcslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.ccsl.xtext.Ccsl");
	}

}
