/*
 * generated by Xtext 2.18.0.M3
 */
package org.ccsl.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCcslScopeProvider extends DelegatingScopeProvider {
}
